# AeroSpace Configuration - Simplified Version

# Start AeroSpace at login
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse behavior
on-focused-monitor-changed = ['move-mouse window-lazy-center']

# Gaps configuration
gaps.inner.horizontal = 8
gaps.inner.vertical = 8
gaps.outer.left = 8
gaps.outer.bottom = 8
gaps.outer.top = 8
gaps.outer.right = 8

# Default layout
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Key bindings - Using alt as the main modifier
[mode.main.binding]

# Focus windows (vim-like)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize windows
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Balance sizes
alt-b = 'balance-sizes'

# Toggle fullscreen
alt-f = 'fullscreen'

# Toggle floating
alt-shift-space = 'layout floating tiling'

# Workspace management
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Reload config
alt-shift-r = 'reload-config'

# Layout changes
alt-t = 'layout tiles horizontal vertical'

# Resize mode
# Note: alt-r may conflict with some apps, so we use alt-shift-e as primary
alt-shift-e = 'mode resize'
# alt-r = 'mode resize'  # Uncomment if no conflicts

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'

# Application-specific rules
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
if.window-title-regex-substring = 'Copy|Move'
run = 'layout floating'

# Keep Ghostty in its current state when creating tabs
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = []  # Don't auto-tile new Ghostty windows